"""
aegis/rewrite_detector.py — LLM Code Rewrite Detector

Uses statistical heuristics (Shannon entropy, comment density, identifier lengths)
to detect code that is "too clean" or stylistically rigid, which often
indicates it was generated by an LLM and potentially variable-renamed.
"""

import ast
import math
import statistics

def calculate_shannon_entropy(text: str) -> float:
    """Calculate the Shannon entropy of a string."""
    if not text:
        return 0.0
    freq = {}
    for char in text:
        freq[char] = freq.get(char, 0) + 1
    entropy = 0.0
    length = len(text)
    for count in freq.values():
        p = count / length
        entropy -= p * math.log2(p)
    return entropy

def analyze_identifiers(source: str) -> dict:
    """Analyze the identifiers used in the code."""
    try:
        tree = ast.parse(source)
    except Exception:
        return {"entropy": 0.0, "avg_length": 0.0, "variance": 0.0}
        
    identifiers = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Name):
            identifiers.append(node.id)
        elif isinstance(node, ast.arg):
            identifiers.append(node.arg)
        elif isinstance(node, ast.FunctionDef):
            identifiers.append(node.name)
        elif isinstance(node, ast.ClassDef):
            identifiers.append(node.name)
            
    if not identifiers:
        return {"entropy": 0.0, "avg_length": 0.0, "variance": 0.0}
        
    concat_ids = "".join(identifiers)
    entropy = calculate_shannon_entropy(concat_ids)
    lengths = [len(i) for i in identifiers]
    avg_length = sum(lengths) / len(lengths)
    variance = statistics.variance(lengths) if len(lengths) > 1 else 0.0
    
    return {
        "entropy": entropy,
        "avg_length": avg_length,
        "variance": variance
    }
    
def calculate_comment_density(source: str) -> float:
    """Calculate the ratio of comment lines to total lines."""
    lines = source.splitlines()
    if not lines:
        return 0.0
    comment_lines = sum(1 for line in lines if line.strip().startswith("#"))
    return comment_lines / len(lines)

def detect_llm_rewrite(source: str) -> dict:
    """
    Combines heuristics to flag potentially LLM-written code.
    LLM code often has:
    - High comment density (overly explanatory)
    - Very consistent identifier lengths (low variance)
    - Descriptive but stereotypical names (affecting entropy)
    """
    id_stats = analyze_identifiers(source)
    comment_density = calculate_comment_density(source)
    
    # Heuristics for "too clean" / LLM-generated:
    # 1. High comment density (LLMs love to explain every step)
    # 2. Low variance in identifier lengths (human code often mixes `i`, `temp`, `my_long_variable_name`)
    
    suspicious_comment = comment_density > 0.20
    suspicious_variance = id_stats["variance"] < 2.0 and id_stats["avg_length"] > 5.0
    
    # Flag if both heuristics trigger (or if it's extremely skewed)
    rewrite_flagged = suspicious_comment and suspicious_variance
    
    return {
        "identifier_entropy": round(id_stats["entropy"], 2),
        "id_length_variance": round(id_stats["variance"], 2),
        "comment_density": round(comment_density, 2),
        "rewrite_flagged": rewrite_flagged
    }
